
    create table products (
        price float(53),
        id bigint generated by default as identity,
        category varchar(255),
        description varchar(255),
        name varchar(255),
        primary key (id)
    );
